name = "jiwonz/greentea_luau"
version = "0.1.0"
description = "A runtime typechecker with Luau types, pretty errors, and inspection"
authors = ["Corecii (Shae A.) <github.com/corecii>", "jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/greentea-luau"
license = "MIT"
includes = ["src/**", "pesde.toml", "LICENSE", "README.md"]

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.3.5", target = "lune" }
multitarget = { name = "jiwonz/multitarget", version = "^0.2.6", target = "lune" }
darklua = { name = "pesde/darklua", version = "^0.16.0", target = "lune" }
